//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechkinApp.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class SpeechkinAppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpeechkinAppSettings defaultInstance = ((SpeechkinAppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpeechkinAppSettings())));
        
        public static SpeechkinAppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.cognitive.microsoft.com/sts/v1.0")]
        public string SpeechAuthUrl {
            get {
                return ((string)(this["SpeechAuthUrl"]));
            }
            set {
                this["SpeechAuthUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string SpeechLanguageDefault {
            get {
                return ((string)(this["SpeechLanguageDefault"]));
            }
            set {
                this["SpeechLanguageDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.cognitive.microsofttranslator.com")]
        public string TranslateUrl {
            get {
                return ((string)(this["TranslateUrl"]));
            }
            set {
                this["TranslateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedDataFlowId {
            get {
                return ((int)(this["SelectedDataFlowId"]));
            }
            set {
                this["SelectedDataFlowId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InputDeviceIndex {
            get {
                return ((int)(this["InputDeviceIndex"]));
            }
            set {
                this["InputDeviceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16000")]
        public int SampleRateValue {
            get {
                return ((int)(this["SampleRateValue"]));
            }
            set {
                this["SampleRateValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int BitsPerSampleValue {
            get {
                return ((int)(this["BitsPerSampleValue"]));
            }
            set {
                this["BitsPerSampleValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChannelValue {
            get {
                return ((int)(this["ChannelValue"]));
            }
            set {
                this["ChannelValue"] = value;
            }
        }
    }
}
